# Generated by Django 5.1.7 on 2026-04-19 08:44

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('student', 'Студент'), ('pickup_point', 'Сотрудник пункта выдачи'), ('admin', 'Администратор')], default='student', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('group_number', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_cat_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(blank=True, choices=[('building', 'Здание'), ('map', 'Карта'), ('free', 'Свободное описание')], max_length=20, null=True)),
                ('location_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('in_pickup', 'В пункте выдачи'), ('has_match', 'Есть совпадение'), ('issued', 'Выдана'), ('closed', 'Закрыта')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, to='main.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Находка',
                'verbose_name_plural': 'Находки',
                'db_table': 'found_item',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50, verbose_name='Тип действия')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Тип сущности')),
                ('entity_id', models.IntegerField(verbose_name='ID сущности')),
                ('action_data', models.TextField(blank=True, null=True, verbose_name='Данные действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'db_table': 'log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('location_text', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('has_match', 'Есть совпадение'), ('closed', 'Закрыта'), ('disputed', 'Спорная ситуация')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, to='main.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пропажа',
                'verbose_name_plural': 'Пропажи',
                'db_table': 'lost_item',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(db_column='found_id', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main.founditem')),
                ('lost_item', models.ForeignKey(db_column='lost_id', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='main.lostitem')),
            ],
            options={
                'verbose_name': 'Сопоставление',
                'verbose_name_plural': 'Сопоставления',
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(blank=True, db_column='found_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.founditem')),
                ('lost_item', models.ForeignKey(blank=True, db_column='lost_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.lostitem')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.ForeignKey(db_column='building_id', on_delete=django.db.models.deletion.RESTRICT, to='main.building')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
                'db_table': 'pickup_point',
            },
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кто выдал')),
                ('found_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issuance', to='main.founditem', verbose_name='Находка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issuances', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issuances', to='main.pickuppoint', verbose_name='Пункт выдачи')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдачи',
                'db_table': 'issuance',
            },
        ),
        migrations.AddField(
            model_name='founditem',
            name='pickup_point',
            field=models.ForeignKey(db_column='pickup_point_id', on_delete=django.db.models.deletion.RESTRICT, to='main.pickuppoint'),
        ),
    ]
