# Generated by Django 5.1.7 on 2026-04-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_founditem_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="founditem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
        migrations.AddField(
            model_name="lostitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
    ]
