# Generated by Django 5.1.7 on 2026-04-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_founditem_image_lostitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founditem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="found_items/"),
        ),
        migrations.AlterField(
            model_name="lostitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_column="category_id",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.category",
            ),
        ),
    ]
