# Generated by Django 5.1.7 on 2026-05-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_founditem_image_alter_lostitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuppoint",
            name="address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Полный адрес"
            ),
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="pickuppoint",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Долгота",
            ),
        ),
    ]
