# Generated by Django 5.1.7 on 2026-05-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_pickuppoint_address_pickuppoint_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickuppoint",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pickuppoint",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
