# Generated by Django 5.1.7 on 2026-05-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
