# Generated by Django 5.1.7 on 2026-05-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_user_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notifications_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
