# Generated by Django 5.1.7 on 2026-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_user_notifications_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
