# Generated by Django 6.0.5 on 2026-06-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_searchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostitem",
            name="pickup_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="main.pickuppoint",
            ),
        ),
    ]
