# Generated by Django 6.0.5 on 2026-06-13 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_lostitem_pickup_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pickup_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.pickuppoint",
                verbose_name="Пункт выдачи (для сотрудников)",
            ),
        ),
    ]
