# Generated by Django 6.0.5 on 2026-06-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-action_time"]},
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="created_at",
            new_name="action_time",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="title",
            new_name="creator_name",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="place",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="subtitle",
        ),
        migrations.AddField(
            model_name="notification",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("claim", "Заявка на вещь"),
                    ("confirm", "Подтверждение выдачи"),
                ],
                default="confirm",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="creator_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="item_category",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="notification",
            name="item_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="item_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="item_title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="pickup_point_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
